import { v } from "convex/values";
import { action, mutation, query } from "./_generated/server";
import { api } from "./_generated/api";

// Email action using Resend - Fixed for free tier
export const sendReportEmailSimple = action({
  args: {
    to: v.string(),
    subject: v.string(),
    reportData: v.string(),
    reportName: v.string(),
    reportFormat: v.string(),
    departmentName: v.optional(v.string()),
    timeRange: v.string(),
    recordCount: v.number(),
  },
  handler: async (ctx, args) => {
    const RESEND_API_KEY = process.env.RESEND_API_KEY!;
    const FROM_EMAIL = "onboarding@resend.dev";
    
    if (!RESEND_API_KEY) {
      throw new Error("RESEND_API_KEY environment variable is not set");
    }

    const { Resend } = await import("resend");
    const resend = new Resend(RESEND_API_KEY);

    const emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center;">
          <h1 style="margin: 0; font-size: 28px;">📊 Samadhan Report</h1>
          <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Automated Report Delivery</p>
        </div>
        
        <div style="padding: 30px; background-color: #f8f9fa;">
          <h2 style="color: #333; margin-bottom: 20px;">📋 ${args.reportName}</h2>
          
          <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px;">
            <h3 style="color: #667eea; margin-bottom: 15px;">Report Summary</h3>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px; font-weight: bold; color: #555;">📅 Time Range:</td>
                <td style="padding: 8px; color: #333;">${args.timeRange}</td>
              </tr>
              <tr style="background-color: #f8f9fa;">
                <td style="padding: 8px; font-weight: bold; color: #555;">📊 Total Records:</td>
                <td style="padding: 8px; color: #333;">${args.recordCount}</td>
              </tr>
              <tr>
                <td style="padding: 8px; font-weight: bold; color: #555;">📁 Format:</td>
                <td style="padding: 8px; color: #333;">${args.reportFormat.toUpperCase()}</td>
              </tr>
              ${args.departmentName ? `
              <tr style="background-color: #f8f9fa;">
                <td style="padding: 8px; font-weight: bold; color: #555;">🏢 Department:</td>
                <td style="padding: 8px; color: #333;">${args.departmentName}</td>
              </tr>
              ` : ''}
              <tr>
                <td style="padding: 8px; font-weight: bold; color: #555;">⏰ Generated:</td>
                <td style="padding: 8px; color: #333;">${new Date().toLocaleString()}</td>
              </tr>
            </table>
          </div>

          <div style="background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <h3 style="color: #667eea; margin-bottom: 15px;">📄 Report Data</h3>
            <pre style="background: #f1f1f1; padding: 15px; border-radius: 5px; overflow-x: auto; font-size: 12px; white-space: pre-wrap; max-height: 400px; overflow-y: auto;">${args.reportData}</pre>
          </div>
        </div>

        <div style="background-color: #f1f3f4; padding: 20px; text-align: center; border-top: 1px solid #e0e0e0;">
          <p style="margin: 0; color: #666; font-size: 14px;">
            🏛️ Generated by <strong>Samadhan Admin Panel</strong><br>
            Civic Issue Management System
          </p>
        </div>
      </div>
    `;

    try {
      const result = await resend.emails.send({
        from: FROM_EMAIL,
        to: "adityashah2701@gmail.com", // Use Resend's test email
        subject: args.subject,
        html: emailContent,
      });

      // Check if there's an error in the response
      if (result.error) {
        throw new Error(`Resend API error: ${result.error.message}`);
      }

      return { 
        success: true, 
        messageId: result.data?.id || 'sent'
      };
    } catch (error) {
      throw error; // Re-throw to see the actual error
    }
  },
});

// Email action (wrapper)
export const sendReportEmail = action({
  args: {
    to: v.string(),
    subject: v.string(),
    reportData: v.string(),
    reportName: v.string(),
    reportFormat: v.string(),
    departmentName: v.optional(v.string()),
    timeRange: v.string(),
    recordCount: v.number(),
  },
  handler: async (ctx, args) => {
    return await ctx.runAction(api.emails.sendReportEmailSimple, args);
  },
});

// Send to all departments (actually sends to verified email with department info)
export const sendReportToAllDepartments = action({
  args: {
    reportData: v.string(),
    reportName: v.string(), 
    reportFormat: v.string(),
    timeRange: v.string(),
    recordCount: v.number(),
    adminEmail: v.string(),
  },
  handler: async (ctx, args) => {
    const departments = await ctx.runQuery(api.departments.getActiveDepartments, {});
    const results = [];

    // Send one email per department to verified email
    for (const department of departments) {
      try {
        const result = await ctx.runAction(api.emails.sendReportEmailSimple, {
          to: "adityashah2701@gmail.com",
          subject: `📊 ${args.reportName} - FOR: ${department.name}`,
          reportData: args.reportData,
          reportName: args.reportName,
          reportFormat: args.reportFormat,
          departmentName: department.name,
          timeRange: args.timeRange,
          recordCount: args.recordCount,
        });

        results.push({
          department: department.name,
          email: "adityashah2701@gmail.com",
          success: result.success,
          messageId: result.messageId,
          error: result.error
        });
      } catch (error) {
        results.push({
          department: department.name,
          email: "adityashah2701@gmail.com",
          success: false,
          error: error instanceof Error ? error.message : "Unknown error"
        });
      }
    }

    return {
      totalDepartments: departments.length,
      successfulSends: results.filter(r => r.success).length,
      failedSends: results.filter(r => !r.success).length,
      results,
      errors: results.filter(r => !r.success)
    };
  },
});

// Send to specific department
export const sendReportToDepartment = action({
  args: {
    departmentId: v.id("departments"),
    reportData: v.string(),
    reportName: v.string(),
    reportFormat: v.string(), 
    timeRange: v.string(),
    recordCount: v.number(),
  },
  handler: async (ctx, args) => {
    const department = await ctx.runQuery(api.departments.getDepartmentById, { id: args.departmentId });
    
    if (!department) {
      return {
        success: false,
        error: "Department not found"
      };
    }

    try {
      const result = await ctx.runAction(api.emails.sendReportEmailSimple, {
        to: "adityashah2701@gmail.com",
        subject: `📊 ${args.reportName} - FOR: ${department.name}`,
        reportData: args.reportData,
        reportName: args.reportName,
        reportFormat: args.reportFormat,
        departmentName: department.name,
        timeRange: args.timeRange,
        recordCount: args.recordCount,
      });

      return {
        success: result.success,
        department: department.name,
        email: "adityashah2701@gmail.com",
        messageId: result.messageId,
        error: result.error
      };
    } catch (error) {
      return {
        success: false,
        department: department.name,
        email: "adityashah2701@gmail.com",
        error: error instanceof Error ? error.message : "Unknown error occurred"
      };
    }
  },
});

// Store email log for tracking
export const logEmailSend = mutation({
  args: {
    recipientEmail: v.string(),
    recipientType: v.string(),
    reportName: v.string(),
    reportFormat: v.string(),
    success: v.boolean(),
    messageId: v.optional(v.string()),
    error: v.optional(v.string()),
    sentBy: v.id("users"),
  },
  handler: async (ctx, args) => {
    return {
      id: Date.now().toString(),
      ...args,
      sentAt: Date.now(),
    };
  },
});
